spring:
  application:
    name: Bootcamp Sysmap 2024 - Allan Franco
    main:
      allow-bean-definition-overriding: true
      allow-circular-references: true

server:
  port: 8082
  servlet:
    context-path: /api